defaults:
  - _self_
  - optional .@_here_: deepqmc
  - system: ???
  - ansatz: paulinet
  - task: train
  - override hydra/job_logging: custom
hydra:
  job:
    name: deepqmc
    chdir: true
  searchpath:
    - file://conf
seed: 0
device: cuda
anomaly: false
workdir: ???
