defaults:
  - _self_
  - omni_factory: omnischnet
_target_: deepqmc.wf.PauliNet.from_hf
mol: ${system}
basis: 6-311g
cas: null
workdir: ${workdir}
init_weights: true
freeze_mos: true
freeze_confs: false
conf_cutoff: 0.01
conf_limit: null
cusp_correction: true
cusp_electrons: true
backflow_type: orbital
backflow_channels: 1
backflow_transform: mult
backflow_op:
  _target_: deepqmc.wf.paulinet.BackflowOp
  mult_act: '${eval:"lambda x: 1 + 2 * torch.tanh(x / 4)"}'
  add_act: '${eval:"lambda x: 0.1 * torch.tanh(x / 4)"}'
  with_envelope: true
rc_scaling: 1.0
cusp_alpha: 10.0
freeze_embed: false
